# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=2, verbose_name='category')),
                ('birth_date', models.DateField()),
                ('weight', models.IntegerField()),
                ('height', models.CharField(max_length=5)),
                ('is_metric', models.BooleanField(help_text='Check if your measurements are in metric units.')),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=62)),
                ('state', models.CharField(choices=[('CO', 'Colorado'), ('MO', 'Missouri'), ('NV', 'Nevada'), ('NY', 'New York'), ('PA', 'Pennsylvania'), ('TX', 'Texas'), ('UT', 'Utah')], default='UT', max_length=3)),
                ('postal_code', models.CharField(max_length=10)),
                ('country', models.CharField(choices=[('US', 'United States')], default='US', max_length=3)),
                ('phone_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('belt_type', models.CharField(choices=[('kyu', 'Kyu - colored belts'), ('dan', 'Dan - black belts')], max_length=4)),
                ('belt_level', models.IntegerField(choices=[('13', '13th'), ('12', '12th'), ('11', '11th'), ('10', '10th'), ('9', '9th'), ('8', '8th'), ('7', '7th'), ('6', '6th'), ('5', '5th'), ('4', '4th'), ('3', '3rd'), ('2', '2nd'), ('1', '1st')], help_text='Belt number level in kyu or dan.')),
                ('years_training', models.IntegerField(help_text='Enter 0 if less than 1 year.')),
                ('events', models.CharField(max_length=8)),
                ('instructor_name', models.CharField(max_length=60)),
                ('dojo_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('has_payment', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'registration',
                'verbose_name_plural': 'registrations',
            },
        ),
    ]
