# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='belt_level',
            field=models.CharField(choices=[('13', '13th'), ('12', '12th'), ('11', '11th'), ('10', '10th'), ('9', '9th'), ('8', '8th'), ('7', '7th'), ('6', '6th'), ('5', '5th'), ('4', '4th'), ('3', '3rd'), ('2', '2nd'), ('1', '1st')], help_text='Belt number level in kyu or dan.', max_length=2),
        ),
        migrations.AlterField(
            model_name='registration',
            name='events',
            field=models.CharField(max_length=40),
        ),
    ]
